name: OCR Service
on:
  workflow_dispatch:
jobs:
  OCR:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "移动一些文件"
        run: |
          mkdir /home/runner/ocr
          mkdir /home/runner/tunnel
          mv * /home/runner/ocr
      - name: "安装内网穿透服务"
        run: |
          cd /home/runner/tunnel
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          
