name: OCR Service
on:
  workflow_dispatch:
jobs:
  OCR:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "移动一些文件"
        run: |
          mkdir /home/runner/ocr
          mkdir /home/runner/tunnel
          mv * /home/runner/ocr
      - name: "安装内网穿透服务"
        run: |
          cd /home/runner/tunnel
          release="wget -qO- -t1 -T2 "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/"\"//g;s/,//g;s/ //g'
          wget https://github.com/cloudflare/cloudflared/releases/download/$release/cloudflared-linux-amd64.deb
          
          
          
          
          
